#!/usr/bin/env bash
help() {
  cat <<EOF
----------------------------------------------------------------------------------------------------------
HELP MESSAGE:

    Usage: c8y oee \\$(basename "$0") [--license <license-string>] [--filePath <path-to-license-file>]
    Arguments:
      -l, --license   license-string        The license string
      -f, --filePath  path-to-license-file  The path to the xml license file
    ***NOTE*** One of these arguments must be used !!!

    Example usage:
      Install Apama license via c8y tenant option by input license key in command line
          c8y oee \install_license --license ABCxyz-key-welcome-to-OEE

      Install Apama license via c8y tenant option by reading xml license file in any directory:
          c8y oee \install_license --filePath "C:/path/to/your/license/file/license_file.xml"

      Install Apama license via c8y tenant option by reading xml license file in c8y-oee/commands/license:
          c8y oee \install_license --filePath .
          -> user is provided a list of files to choose

          c8y oee \install_license --filePath ./license/license_file.xml
          -> The referred file is used

----------------------------------------------------------------------------------------------------------
EOF
}

error_check() {
  if [ $? -ne 0 ]; then
    echo "Error: process failed"
    exit 1
  fi
}


# Parse command-line options
REST_ARGS=()
while [ $# -gt 0 ]; do
  case "$1" in
    -h|--help)
      help
      exit 0
      ;;
    -l|-license|--license)
      if [ $# -gt 1 ]; then
        LICENSE_UNESCAPED=$2
        shift
      else
        echo "Option $1 requires an argument." >&2
        exit 1
      fi
      ;;
    -f|-filePath|--filePath)
      if [ $# -gt 1 ]; then
        FILEPATH=$2
        shift
      else
        echo "Option $1 requires an argument." >&2
        exit 1
      fi
      ;;
    *)
      REST_ARGS+=("$1")
      ;;
  esac
  shift
done

# Check if license string was input in command line
missing_args=()
if [[ -z $LICENSE_UNESCAPED ]]; then
  if [[ -z $FILEPATH ]]; then
    # Add filePath argument to missing message
    missing_args+=(filePath)
    :
  fi
  # input filepath is . or ./example.xml
  if [[ $FILEPATH == "."* ]]; then
    # Check script current directory and move to license directory inside it.
    script_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
    cd "$script_dir/license"
    error_check

    # input file path is ./example.xml
    if [[ $FILEPATH != "." ]]; then
      license_filename=$(basename "$FILEPATH")
      license_filepath="$script_dir/license/$license_filename"

    # input file path is .
    else
      # List all files in directory and prompt user to choose one
      files=($(ls))
      echo "Please choose a file to read:"
      select file in "${files[@]}"; do
        if [[ -n $file ]]; then
          license_filepath="$script_dir/license/$file"
          break
        fi
      done
      license_filename=$file
    fi

  else
    license_filepath=$FILEPATH
    # Extract filename from full path
    license_filename=$(basename "$license_filepath")
    # Extract directory path from full path
    filepath_without_filename=$(dirname "$license_filepath")
    # Change to directory containing license file
    cd "$filepath_without_filename"
    error_check

  fi

  # Read license xml file
  LICENSE_UNESCAPED=$(cat "$license_filename")
  error_check

fi

# Add license argument to missing message
if [[ -z $LICENSE_UNESCAPED ]]; then
  missing_args+=(license)
fi

# If no license string exists by input or in file, show error message
if [[ ${#missing_args[@]} -gt 0 ]]; then
  message="Error: Missing one of required arguments: ${missing_args[0]}"
  for (( i=1; i<${#missing_args[@]}; i++ )); do
    message+=", ${missing_args[$i]}"
  done
  echo "$message" >&2
  echo "License variable not set. Use -l|--license to set the license or --filePath to point to the license xml file." >&2
  help
  exit 1
fi

set -- "${REST_ARGS[@]}"

# Remove new line and return characters from license content
LICENSE_ESCAPED=$(echo "$LICENSE_UNESCAPED" | tr -d '\r\n')

echo "URL          :  $C8Y_HOST"
echo "Tenant ID    :  $C8Y_TENANT"
echo "User         :  $C8Y_USER"
if [ -n "$license_filepath" ]; then
  echo "License file :  $license_filepath"
fi

echo "License is being installed"

response=$(c8y tenantoptions update --category apama --key credentials.license --value "$LICENSE_ESCAPED" 2>&1)
if [[ $response == *"serverError"* || -z $response ]]; then
  echo "$response"
  echo "Error: Failed to add apama license to tenant option." >&2
  exit 1
fi

echo "License is installed successfully"