# yaml-language-server: $schema=https://raw.githubusercontent.com/reubenmiller/go-c8y-cli/feat/extensions-manager/tools/schema/extensionCommands.json
---
group:
  name: profiles
  description: OEE profiles/configurations

commands:
  - name: list
    description: Get all profiles
    method: GET
    path: service/oee-bundle/configurationmanager/2/configuration

  - name: get
    description: Get profile
    descriptionLong: Get the profile with the given configurationId
    method: GET
    path: service/oee-bundle/configurationmanager/2/configuration/{id}
    pathParameters:
      - name: id
        type: string
        description: Profile/Configuration id
        pipeline: true

  - name: delete
    description: Delete profile
    method: DELETE
    path: service/oee-bundle/configurationmanager/2/configuration/{id}
    pathParameters:
      - name: id
        type: string
        description: Profile/Configuration id
        pipeline: true

  - name: create
    description: Create profile
    method: POST
    path: service/oee-bundle/configurationmanager/2/configuration
    exampleList:
      - description: Create a new OEE profile named "testing" for device with ID 12345 by using profile.jsonnet template in templates directory and make change to some fields
        command: c8y oee profiles create --template oee::profile.jsonnet --deviceId 12345 --name testing --type MACHINE --status INACTIVE
    bodyRequiredKeys:
      - "deviceId"
      - "name"
    body:
      - name: type
        type: string
        description: Type
        default: MACHINE
        validationSet:
          - "MACHINE"
          - "LINE"
      
      - name: deviceId
        type: string
        description: ID of parent device
          
      - name: name
        type: string
        description: Name of profile

      - name: locationId
        type: string
        description: Name of shiftplan
        default: " "

      - name: status
        type: string
        description: Status of the Profile
        default: INCOMPLETE
        validationSet:
          - "INACTIVE"
          - "ACTIVE"
          - "INCOMPLETE"

      - name: availability
        type: integer
        property: oeeTargets.availability
        description: OEE target availability
        default: 80

      - name: performance
        type: integer
        property: oeeTargets.performance
        description: OEE target performance
        default: 80

      - name: overall
        type: integer
        property: oeeTargets.overall
        description: OEE target overall
        default: 80
      
      - name: quality
        type: integer
        property: oeeTargets.quality
        description: OEE target quality
        default: 80

  - name: update
    description: Update profile
    descriptionLong: Update
    method: PUT
    path: service/oee-bundle/configurationmanager/2/configuration/{id}
    pathParameters:
      - name: id
        type: string
        description: Profile/Configuration id
        pipeline: true
    body:
      - name: name
        type: string
        description: Profile name

      - name: type
        type: string
        description: Profile type
        validationSet:
          - MACHINE
          - LINE

      - name: deviceId
        type: '[]device'
        description: Device ID

      - name: tenantId
        type: tenant
        description: tenant Id (defaults to current tenant)
      
      - name: amountUnit
        type: string
        description: Amount unit

      - name: external
        type: boolean
        description: External

      - name: testConfiguration
        property: testConfiguration
        type: boolean
        description: Test profile/configuration

      - name: status
        type: string
        description: Status
        validationSet:
          - ACTIVE
          - INACTIVE
          - INCOMPLETE
